### ISSUE TITLE
V. 6.1 Servos don't work

### ISSUE THREAD

**Issue by Frenazo** [TheDIYGuy999/Rc_Engine_Sound_ESP32#16]
Hi.
thank you so much for this amazing project.
I have a board with version 6.1 installed, connected by Sbus and all sounds, lights and motor work perfectly, however I can't get the servos to work connected to the PCB board terminals. If I connect the servos directly to the receiver they do work. Attached photo of the connections.
Thanks a lot.
P.D .: I am Oscar Moreno oscarveterinario from youtube, xD
![IMG_20201229_175225](https://user-images.githubusercontent.com/70027407/103312387-24646b80-4a1d-11eb-9c85-4c643d665ba0.jpg)
![IMG_20201229_175331](https://user-images.githubusercontent.com/70027407/103312389-24fd0200-4a1d-11eb-9a45-559eb6fdc36f.jpg)

**Comment by TheDIYGuy999** [comment]
Hi Oscar,
thanks for the praise. This behaviour  is normal. You can't connect the servos to the ESP32 board in SBUS mode, there are no RC signal outputs. The only exception is the ESC output. This means, you have to connect the servos directly to the receiver.

**Comment by Frenazo** [comment]
Thanks!
