### ISSUE TITLE
Fuse

### ISSUE THREAD

**Issue by Frenazo** [TheDIYGuy999/Rc_Engine_Sound_ESP32#18]
Hello Martin.

As always: GREAT JOB!!!

You recommended to use a fuse between the battery and the sound controller / ESC, ¿what kind of fuse?

Thanks

**Comment by TheDIYGuy999** [comment]
Hi,
the easiest solution is a car fuse in the battery + wire. Rating as low as possible, depending on the size of your car.

**Comment by Frenazo** [comment]
Thanks
5A is enough or is it too much?

**Comment by TheDIYGuy999** [comment]
Depends on you motor and ESC
