### ISSUE TITLE
5V use from BEC ?

### ISSUE THREAD

**Issue by Skirmitt83** [TheDIYGuy999/Rc_Engine_Sound_ESP32#19]
Hi, Is there a specific reason there is a 5V voltage regulator used  on the board instead of the 5V BEC ?
Also a small hint to use a LDO regulator that works from around 5.5 - 6V.
Just ordered the SMD PCB :-)

**Comment by babajun12** [comment]
Indeed, I attached an ESC with 6V BEC and fried the sound amplifier module while I bridged the BEC voltage to the +5V terminal.
