### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by klimma1508** [TheDIYGuy999/Rc_Engine_Sound_ESP32#21]
Hello, I tryed to uploatd Your program to esp32, but it write that error. Where can be probem? Thank you Klimš
<img width="960" alt="error" src="https://user-images.githubusercontent.com/55253868/113484601-7a77fd80-94a9-11eb-9baa-8562193653ea.png">

**Comment by TheDIYGuy999** [comment]
Install all required libraries according to the documentation
