### ISSUE TITLE
question: a different way to change the engine speed

### ISSUE THREAD

**Issue by fisenkodv** [TheDIYGuy999/Rc_Engine_Sound_ESP32#50]
Is it possible to use the Hall sensor to emulate the engine speed instead of RC controller? The idea is I have a bike's wheel and based on the wheel rotational speed change the sound of the engine. Any ideas, links, etc. are appreciated.

**Comment by isopix** [comment]
Hall sensor?

Simple "Proximity Sensor" (using magnet too, but digital. It doesn't need analog or precision at all).
