### ISSUE TITLE
Board rebooting with latest ESP Board versions

### ISSUE THREAD

**Issue by SalmanSheikIsmail** [TheDIYGuy999/Rc_Engine_Sound_ESP32#51]
Board reboots when the Arduino code is compiled using ESP32 board versions after 1.0.5.

**Comment by Faberonline** [comment]
> Board reboots when the Arduino code is compiled using ESP32 board versions after 1.0.5.

Is there a fix??? I have the same problem... Is it the bootloader or ..?

**Comment by TheDIYGuy999** [comment]
Currently, there is no other fix than using board version 1.0.5
