### ISSUE TITLE
Tank mode

### ISSUE THREAD

**Issue by SJoWie80** [TheDIYGuy999/Rc_Engine_Sound_ESP32#53]
Hello 

If i use it in tank mode en add the 2 esc to ch2 en ch3 on the esp pcb it doesnt work. I hear the sounds etc but the esc do not respond am i doing something wrong? 

Regards 
Joey

**Comment by TheDIYGuy999** [comment]
Tank mode does not support ESC output. You have to control them directly from your transmitter
