### ISSUE TITLE
Control issues volume dependant

### ISSUE THREAD

**Issue by Whitey092** [TheDIYGuy999/Rc_Engine_Sound_ESP32#59]
Hi Martin, 
I’m having an issue with control dependant on volume. 
There is no issue when at maximum and 1 notch down. 
At lowest and muted volume levels any speed/throttle/brake settings are ignored. The ESC accelerates as if it is not controlled by the board, will not brake and has no inertia.

I made a new board with a new esp32 just to rule that out but it didn’t make a difference.

**Comment by FBester1976** [comment]
Hello,

The board is put in "Crawler mode" based on values in 8_adjustmentsSound.h. So, in crawler mode the virtual inertia is disabled.

If you do not want Crawler mode, you need to make the **masterVolumeCrawlerThreshold** less than the lowest Volume percentage you have. If you make the masterVolumeCrawlerThreshold = 43 or less, you will not have Crawler mode for the current selection below.
 
// Volume adjustment
const  uint8_t numberOfVolumeSteps = 3; // The mumber of volume steps below
const uint8_t masterVolumePercentage[] = {100, 66, **44**}; // loud, medium, silent (more than 100% may cause distortions)

//const  uint8_t numberOfVolumeSteps = 4; // The mumber of volume steps below
//const uint8_t masterVolumePercentage[] = {100, 66, **44**, 0}; // loud, medium, silent, no sound (more than 100% may cause distortions)

// Crawler mode
const uint8_t **masterVolumeCrawlerThreshold** = **44**; // If master volume is <= this threshold, crawler mode (without virtual inertia) is active

Hope this helps...

**Comment by TheDIYGuy999** [comment]
Thank you, Frikkie!

**Comment by Whitey092** [comment]
Ahhh perfect! Thank you. 
I have one more question.
When using Virtual 3 Speed and wireless trailers, the truck engine sound goes to full rev as soon as you start the truck. If I move the throttle a little bit it comes back down. But with throttle at neutral it revs high. Am I missing something that controls that?

**Comment by FBester1976** [comment]
Some basic questions:

What remote do you use?
Do you have a self-centring spring on the throttle?
Do you always switch the remote on before the truck?
Possible to make a video? Youtube link?

**Comment by Whitey092** [comment]
Hi Frikkie, 
Thanks for your response. I am using Flysky Paladin EV. Self centering sticks, and yes transmitter always powered on before reciever.

As I said this only happens with wireless trailers enabled. If I uncommonly wireless trailer it works perfectly. 

Here is a YouTube short link:
https://youtube.com/shorts/ncpT9OmvEzY?feature=share

I have tried it with trailers connected also but it does not fix the problem.
