### ISSUE TITLE
Add RPM sensor support

### ISSUE THREAD

**Issue by artistru** [TheDIYGuy999/Rc_Engine_Sound_ESP32#6]
Hello. Your project is amazing! But i want suggest some improvements. For sport cars the best way to simulate engine sound, tones, sounds of virtual gear shifting is using real motor RPM instead throttle signal form receiver. For your arduino project i was modify the code to use HobbyWing RPM sensor, but in this project i have no skills to do this.
Do you have the desire and time to add support for this sensor?

**Comment by TheDIYGuy999** [comment]
Good idea, but with the recommended crawler ESC you will not need it, because the RPM is in synch with the output signal.
