### ISSUE TITLE
D1 on PCB schematic not connected(not defined)

### ISSUE THREAD

**Issue by praji181** [TheDIYGuy999/Rc_Engine_Sound_ESP32#9]
hi there

I went through the schematic and i found that on the ESP32 30 pin board, D1( IO 1) is not connected to any point. i am sorry if i missed out anything, but can you clarify, if it is a problem with the schematic, or if that is a dummy(un used pin)

thank you

**Comment by TheDIYGuy999** [comment]
Hi,
this is correct. You will have boot problems, if this pin is pulled down while powering up. For example, you can't drive an NPN transistor with 1k base resistor. So I moved the headlights to pin 0 for the 30 pin board.
